"""add qc_status

Revision ID: 64169cbf3b78
Revises: 2a8e289b8c95
Create Date: 2026-06-30 13:18:32.170328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64169cbf3b78'
down_revision: Union[str, None] = '2a8e289b8c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_records', sa.Column('delivered_time', sa.DateTime(), nullable=True))
    op.add_column('dispatch_records', sa.Column('receiver_name', sa.String(), nullable=True))
    op.add_column('dispatch_records', sa.Column('receiver_signature', sa.Text(), nullable=True))
    op.add_column('dispatch_records', sa.Column('delivery_photo', sa.String(), nullable=True))
    op.add_column('dispatch_records', sa.Column('delivery_remarks', sa.Text(), nullable=True))
    op.add_column('qc_records', sa.Column('inspector_id', sa.Integer(), nullable=True))
    op.add_column('qc_records', sa.Column('stage', sa.String(), nullable=False))
    op.add_column('qc_records', sa.Column('status', sa.String(), nullable=True))
    op.add_column('qc_records', sa.Column('expected_time', sa.DateTime(), nullable=True))
    op.add_column('qc_records', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('qc_records', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('qc_records', sa.Column('checklist', sa.JSON(), nullable=True))
    op.add_column('qc_records', sa.Column('photos', sa.JSON(), nullable=True))
    op.add_column('qc_records', sa.Column('signature', sa.JSON(), nullable=True))
    op.alter_column('qc_records', 'inspector_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('qc_records', 'inspected_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('qc_records', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'qc_records', 'users', ['inspector_id'], ['id'], ondelete='SET NULL')
    op.add_column('vehicles', sa.Column('qc_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'qc_status')
    op.drop_constraint(None, 'qc_records', type_='foreignkey')
    op.alter_column('qc_records', 'result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('qc_records', 'inspected_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('qc_records', 'inspector_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('qc_records', 'signature')
    op.drop_column('qc_records', 'photos')
    op.drop_column('qc_records', 'checklist')
    op.drop_column('qc_records', 'end_time')
    op.drop_column('qc_records', 'start_time')
    op.drop_column('qc_records', 'expected_time')
    op.drop_column('qc_records', 'status')
    op.drop_column('qc_records', 'stage')
    op.drop_column('qc_records', 'inspector_id')
    op.drop_column('dispatch_records', 'delivery_remarks')
    op.drop_column('dispatch_records', 'delivery_photo')
    op.drop_column('dispatch_records', 'receiver_signature')
    op.drop_column('dispatch_records', 'receiver_name')
    op.drop_column('dispatch_records', 'delivered_time')
    # ### end Alembic commands ###
