"""add logistics fields

Revision ID: 728cc73fa963
Revises: 35a9f15f52be
Create Date: 2026-06-26 12:43:47.818432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728cc73fa963'
down_revision: Union[str, None] = '35a9f15f52be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('driver_name', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('driver_mobile_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('transport_company', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('truck_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('lr_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('dispatch_challan_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('dispatch_date_time', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('expected_arrival_date_time', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('documents_url', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'rejection_reason')
    op.drop_column('vehicles', 'remarks')
    op.drop_column('vehicles', 'documents_url')
    op.drop_column('vehicles', 'expected_arrival_date_time')
    op.drop_column('vehicles', 'dispatch_date_time')
    op.drop_column('vehicles', 'dispatch_challan_number')
    op.drop_column('vehicles', 'invoice_number')
    op.drop_column('vehicles', 'lr_number')
    op.drop_column('vehicles', 'truck_number')
    op.drop_column('vehicles', 'transport_company')
    op.drop_column('vehicles', 'driver_mobile_number')
    op.drop_column('vehicles', 'driver_name')
    # ### end Alembic commands ###
