"""update_schema

Revision ID: 92bd27ad11dc
Revises: ddcde0946873
Create Date: 2026-06-29 17:16:53.791621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bd27ad11dc'
down_revision: Union[str, None] = 'ddcde0946873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('punch_in_photo_url', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('punch_out_photo_url', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('net_working_hours', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('break_time', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('late_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('early_exit_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance_logs', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('attendance_logs', sa.Column('address', sa.String(), nullable=True))
    op.add_column('attendance_logs', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('attendance_logs', sa.Column('network_type', sa.String(), nullable=True))
    op.add_column('attendance_logs', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('attendance_logs', 'photo_url')
    op.drop_column('attendance_logs', 'network_type')
    op.drop_column('attendance_logs', 'speed')
    op.drop_column('attendance_logs', 'address')
    op.drop_column('attendance_logs', 'accuracy')
    op.drop_column('attendance', 'early_exit_minutes')
    op.drop_column('attendance', 'late_minutes')
    op.drop_column('attendance', 'break_time')
    op.drop_column('attendance', 'net_working_hours')
    op.drop_column('attendance', 'punch_out_photo_url')
    op.drop_column('attendance', 'punch_in_photo_url')
    # ### end Alembic commands ###
