"""Add worker password

Revision ID: aa71f60ef10c
Revises: 82151ba7ede2
Create Date: 2026-06-24 12:47:03.737270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa71f60ef10c'
down_revision: Union[str, None] = '82151ba7ede2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'password')
    # ### end Alembic commands ###
