"""gate_entry_fields

Revision ID: d056706fef48
Revises: 92bd27ad11dc
Create Date: 2026-06-29 17:43:35.913198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd056706fef48'
down_revision: Union[str, None] = '92bd27ad11dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('gate_entry_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('hold_reason', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('expected_resolution', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('dispatch_location', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('current_location', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('arrival_location', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('dispatch_coordinates', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('arrival_coordinates', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicles_gate_entry_number'), 'vehicles', ['gate_entry_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_gate_entry_number'), table_name='vehicles')
    op.drop_column('vehicles', 'arrival_coordinates')
    op.drop_column('vehicles', 'dispatch_coordinates')
    op.drop_column('vehicles', 'arrival_location')
    op.drop_column('vehicles', 'current_location')
    op.drop_column('vehicles', 'dispatch_location')
    op.drop_column('vehicles', 'expected_resolution')
    op.drop_column('vehicles', 'hold_reason')
    op.drop_column('vehicles', 'gate_entry_number')
    # ### end Alembic commands ###
