"""Add vehicle verification fields

Revision ID: ddcde0946873
Revises: d3991fbc31b9
Create Date: 2026-06-26 15:41:45.073698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcde0946873'
down_revision: Union[str, None] = 'd3991fbc31b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('verification_status', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('verified_by', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('arrival_time', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('arrival_photos', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('platform_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('dealer_name', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('submitted_by_oem', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('gate_entry_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'gate_entry_time')
    op.drop_column('vehicles', 'submitted_at')
    op.drop_column('vehicles', 'submitted_by_oem')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'vehicle_model')
    op.drop_column('vehicles', 'dealer_name')
    op.drop_column('vehicles', 'vin')
    op.drop_column('vehicles', 'chassis_number')
    op.drop_column('vehicles', 'platform_number')
    op.drop_column('vehicles', 'verification_notes')
    op.drop_column('vehicles', 'arrival_photos')
    op.drop_column('vehicles', 'arrival_time')
    op.drop_column('vehicles', 'verified_at')
    op.drop_column('vehicles', 'verified_by')
    op.drop_column('vehicles', 'verification_status')
    # ### end Alembic commands ###
