"""Add payroll advances and records

Revision ID: 35a9f15f52be
Revises: aa71f60ef10c
Create Date: 2026-06-24 15:05:17.600505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a9f15f52be'
down_revision: Union[str, None] = 'aa71f60ef10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
