"""Add advanced employee and salary fields

Revision ID: 60e23440c98e
Revises: 2408f5a18520
Create Date: 2026-06-24 11:49:47.763995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e23440c98e'
down_revision: Union[str, None] = '2408f5a18520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_profiles', sa.Column('sunday_rate_per_hour', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('employment_status', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('shift_type', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('emergency_contact_number', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('aadhaar_number', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('face_registration_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'face_registration_status')
    op.drop_column('workers', 'pan_number')
    op.drop_column('workers', 'aadhaar_number')
    op.drop_column('workers', 'address')
    op.drop_column('workers', 'emergency_contact_relationship')
    op.drop_column('workers', 'emergency_contact_number')
    op.drop_column('workers', 'emergency_contact_name')
    op.drop_column('workers', 'shift_type')
    op.drop_column('workers', 'employment_status')
    op.drop_column('workers', 'gender')
    op.drop_column('workers', 'date_of_birth')
    op.drop_column('workers', 'email')
    op.drop_column('salary_profiles', 'sunday_rate_per_hour')
    # ### end Alembic commands ###
