"""add audit fields

Revision ID: fa87ffae5906
Revises: 64169cbf3b78
Create Date: 2026-07-01 11:11:59.501819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa87ffae5906'
down_revision: Union[str, None] = '64169cbf3b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_events', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('activity_events', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('activity_events', sa.Column('edited_by', sa.String(), nullable=True))
    op.add_column('activity_events', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_events', 'reason')
    op.drop_column('activity_events', 'edited_by')
    op.drop_column('activity_events', 'new_value')
    op.drop_column('activity_events', 'old_value')
    # ### end Alembic commands ###
